import React from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useApp } from '../context/AppContext';
import { colors } from '../theme';

export function NotificationSettingsScreen() {
  const { notificationEnabled, setNotificationEnabled } = useApp();
  return <View style={styles.screen}><View style={styles.setting}><View style={styles.settingText}><Text style={styles.label}>Trail notifications</Text><Text style={styles.status}>{notificationEnabled ? 'Enabled' : 'Disabled'}</Text></View><Switch value={notificationEnabled} onValueChange={setNotificationEnabled} accessibilityRole="switch" accessibilityLabel="Trail notifications" accessibilityHint="Changes your locally stored notification preference" accessibilityState={{ checked: notificationEnabled }} trackColor={{ false: colors.switchTrackOff, true: colors.switchTrackOn }} thumbColor={colors.switchThumb} /></View><Text style={styles.note}>This prototype stores your preference locally. It does not send real notifications.</Text></View>;
}
export function UnitsScreen() { const { preferredUnits, setPreferredUnits } = useApp(); return <View style={styles.screen}><Text style={styles.intro}>Choose how distance and elevation are displayed throughout TrailMate.</Text>{['Imperial', 'Metric'].map(value => <Pressable key={value} onPress={() => setPreferredUnits(value)} accessibilityRole="radio" accessibilityLabel={`Use ${value.toLowerCase()} units`} accessibilityState={{ selected: preferredUnits === value, checked: preferredUnits === value }} style={({ pressed }) => [styles.choice, pressed && styles.pressed]}><View style={styles.settingText}><Text style={styles.label}>{value}</Text><Text style={styles.choiceSub}>{value === 'Imperial' ? 'Miles and feet' : 'Kilometers and meters'}</Text></View><Ionicons name={preferredUnits === value ? 'radio-button-on' : 'radio-button-off'} size={26} color={preferredUnits === value ? colors.primary : colors.iconMuted} /></Pressable>)}</View>; }
export function AboutScreen() { return <View style={styles.screen}><Ionicons name="leaf" size={46} color={colors.primary} /><Text style={styles.aboutTitle}>TrailMate</Text><Text style={styles.version}>Version 1.0.0</Text><Text style={styles.about}>TrailMate helps hikers discover, review, and save trails.</Text><Text style={styles.note}>Trail information and route previews are mocked for this class prototype.</Text></View>; }
const styles = StyleSheet.create({ screen:{flex:1,backgroundColor:colors.background,padding:24}, setting:{borderTopWidth:1,borderBottomWidth:1,borderColor:colors.borderSubtle,paddingVertical:18,paddingHorizontal:2,flexDirection:'row',alignItems:'center'}, settingText:{flex:1,paddingRight:20}, label:{fontSize:18,fontWeight:'800',color:colors.textPrimary}, status:{fontSize:16,color:colors.textSecondary,marginTop:5}, note:{fontSize:16,color:colors.textSecondary,lineHeight:24,marginTop:22}, intro:{fontSize:16,color:colors.textSecondary,lineHeight:24,marginBottom:14}, choice:{minHeight:78,paddingVertical:13,borderBottomWidth:1,borderColor:colors.borderSubtle,flexDirection:'row',alignItems:'center',justifyContent:'space-between'}, choiceSub:{fontSize:15,color:colors.textSecondary,marginTop:4}, pressed:{opacity:.7}, aboutTitle:{fontSize:31,fontWeight:'900',color:colors.textPrimary,marginTop:12}, version:{fontSize:16,color:colors.textSecondary,marginTop:2}, about:{fontSize:18,lineHeight:27,color:colors.textPrimary,marginTop:35} });
