import React from 'react';
import { Alert, Linking, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useApp } from '../context/AppContext';
import { trailById } from '../data/trails';
import TrailImage from '../components/TrailImage';
import DifficultyBadge from '../components/DifficultyBadge';
import { colors, shadow } from '../theme';
import { formatDistance, formatElevation, formatTime } from '../utils/formatting';

function RoutePreview({ trail }) { return <View accessible accessibilityLabel={`Illustrative route preview for ${trail.name}. Not a live map.`} style={styles.route}><View style={[styles.contour, { top: 10, width: '80%' }]} /><View style={[styles.contour, { top: 38, width: '65%', left: '25%' }]} /><View style={[styles.contour, { top: 70, width: '92%', left: '-8%' }]} /><View style={styles.path} /><View style={styles.marker}><Ionicons name="location" size={18} color={colors.onPrimary} /></View><Text style={styles.routeLabel}>Illustrative route preview</Text></View>; }

export default function TrailDetailsScreen({ route, navigation }) {
  const insets = useSafeAreaInsets(); const trail = trailById(route.params?.trailId); const { isTrailSaved, toggleSavedTrail, preferredUnits } = useApp(); const overlayTop = insets.top + 12;
  if (!trail) return <View style={styles.error}><Ionicons name="warning-outline" size={44} color={colors.difficultyModerate} /><Text style={styles.errorTitle}>Trail not found</Text><Text style={styles.errorText}>This trail may no longer be available.</Text><Pressable onPress={() => navigation.goBack()} style={styles.return}><Text style={styles.returnText}>Return to trails</Text></Pressable></View>;
  const start = async () => { const label = encodeURIComponent(trail.name); const { latitude, longitude } = trail.trailhead; const url = Platform.OS === 'ios' ? `http://maps.apple.com/?daddr=${latitude},${longitude}&q=${label}` : `geo:${latitude},${longitude}?q=${latitude},${longitude}(${label})`; try { if (!(await Linking.canOpenURL(url))) throw new Error('unsupported'); await Linking.openURL(url); } catch { Alert.alert('Unable to open maps', 'Directions could not be opened on this device.'); } };
  const metrics = [['location', formatDistance(trail.distanceMiles, preferredUnits), 'Distance'], ['triangle', formatElevation(trail.elevationGainFeet, preferredUnits), 'Elevation'], ['time', formatTime(trail.estimatedMinutes), 'Time']];
  return <View style={styles.screen}><ScrollView contentContainerStyle={styles.scroll}><View style={styles.hero}><TrailImage trail={trail} hero style={styles.heroImage} /></View><View style={styles.body}><View style={styles.titleRow}><Text style={styles.title}>{trail.name}</Text><DifficultyBadge difficulty={trail.difficulty} /></View><View style={styles.metrics}>{metrics.map(([icon, value, label], index) => <View key={label} style={[styles.metric, index > 0 && styles.metricBorder]}><Ionicons name={icon} size={25} color={colors.iconMuted} /><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>)}</View><View style={styles.divider} /><Text style={styles.sectionTitle}>Description</Text><Text style={styles.description}>{trail.fullDescription}</Text><RoutePreview trail={trail} /><Pressable onPress={start} accessibilityRole="button" accessibilityLabel={`Start navigation to ${trail.name}`} accessibilityHint="Opens directions in your device’s maps application" style={({ pressed }) => [styles.start, pressed && styles.startPressed]}><Text style={styles.startText}>Start Navigation</Text></Pressable></View></ScrollView><Pressable onPress={() => navigation.goBack()} style={[styles.overlay, { top: overlayTop }]} accessibilityRole="button" accessibilityLabel="Go back" accessibilityHint="Returns to the previous screen"><Ionicons name="arrow-back" size={29} color={colors.overlayIcon} /></Pressable><Pressable onPress={() => toggleSavedTrail(trail.id)} style={[styles.overlay, styles.save, { top: overlayTop }]} accessibilityRole="button" accessibilityLabel={isTrailSaved(trail.id) ? `Remove ${trail.name} from saved trails` : `Save ${trail.name}`} accessibilityState={{ selected: isTrailSaved(trail.id) }}><Ionicons name={isTrailSaved(trail.id) ? 'star' : 'star-outline'} size={29} color={isTrailSaved(trail.id) ? colors.favorite : colors.textPrimary} /></Pressable></View>;
}

const styles = StyleSheet.create({ screen:{flex:1,backgroundColor:colors.background}, scroll:{paddingBottom:28}, hero:{height:265,position:'relative'}, heroImage:{width:'100%',height:'100%'}, overlay:{position:'absolute',left:16,width:52,height:52,borderRadius:26,backgroundColor:colors.overlaySurface,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.onPrimary,...shadow}, save:{left:undefined,right:16,backgroundColor:colors.surface}, body:{padding:20}, titleRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10}, title:{flex:1,fontSize:26,fontWeight:'900',color:colors.textPrimary,lineHeight:32}, metrics:{flexDirection:'row',marginTop:18,paddingVertical:15,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.borderSubtle}, metric:{flex:1,alignItems:'center'}, metricBorder:{borderLeftWidth:1,borderColor:colors.borderSubtle}, metricValue:{fontSize:16,fontWeight:'800',color:colors.textPrimary,marginTop:4}, metricLabel:{fontSize:14,color:colors.textSecondary,marginTop:3}, divider:{height:1,backgroundColor:colors.borderSubtle,marginTop:20}, sectionTitle:{fontSize:21,fontWeight:'900',color:colors.textPrimary,marginTop:20}, description:{fontSize:16,color:colors.textSecondary,lineHeight:25,marginTop:10}, route:{height:150,borderRadius:15,overflow:'hidden',backgroundColor:'#DCE9C5',borderWidth:1,borderColor:colors.border,marginTop:20,position:'relative'}, contour:{position:'absolute',height:40,borderRadius:30,borderWidth:1,borderColor:'#74835F',transform:[{rotate:'-8deg'}]}, path:{position:'absolute',height:10,width:'74%',left:'12%',top:75,borderRadius:12,backgroundColor:colors.primary,transform:[{rotate:'-10deg'}]}, marker:{position:'absolute',left:'18%',top:55,width:29,height:29,borderRadius:15,backgroundColor:'#1F75A5',alignItems:'center',justifyContent:'center'}, routeLabel:{position:'absolute',bottom:8,right:10,fontSize:12,color:'#40512F',fontWeight:'700'}, start:{height:62,borderRadius:14,marginTop:20,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',...shadow}, startPressed:{backgroundColor:colors.primaryPressed}, startText:{color:colors.onPrimary,fontSize:21,fontWeight:'900'}, error:{flex:1,alignItems:'center',justifyContent:'center',padding:30}, errorTitle:{fontSize:24,fontWeight:'900',marginTop:12,color:colors.textPrimary}, errorText:{fontSize:16,color:colors.textSecondary,marginTop:6}, return:{marginTop:20,backgroundColor:colors.primary,padding:14,borderRadius:10}, returnText:{color:colors.onPrimary,fontWeight:'800'} });
